name: "BCRS CD action"
author: "Patrick Wei"
description: "CD for BCRS projects"
branding:
  icon: "check"
  color: "blue"
inputs:
  WORKING_DIRECTORY:
    description: "The application directory"
    required: true
  APP_NAME:
    description: "The application name"
    required: true
  VAULTS:
    description: "The 1password vaults"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build image
      shell: bash
      working-directory: ${WORKING_DIRECTORY}
      run: |
        pwd
        docker build . --file Dockerfile --tag image

    - name: Install tools (1password)
      shell: bash
      run: |
        ${{ github.action_path }}/install_tools.sh
        oc version
        op --version
